datasource:
  db:
    driver: org.sqlite.JDBC
    url: jdbc:sqlite:a.db
    username: "" # No se requiere usuario en SQLite
    password: "" # No se requiere contraseña en SQLite
    dialect: sqlite
    isolationLevel: READ_COMMITTED

ebean:
  server:
    db:
      packages: org.conagua
      databasePlatform: sqlite
      migration: false
      updateChangesOnly: true
      ddlGenerate: true # Genera el esquema de base de datos automáticamente
      ddlRun: true # Ejecuta las declaraciones DDL para crear las tablas
